import {invoicePdf} from '@/lib/pdf';
import {getRuntimeEnv} from '@/lib/runtime';
import {App} from '@/lib/backend';
import {ServiceError,austin,ptero} from '@/lib/adapters';
import {id,now,random,password,sha,invoice,hmac} from '@/lib/crypto';
import {catalog,defaults} from '@/lib/catalog';
export const dynamic='force-dynamic';
export const runtime='nodejs';
export const maxDuration=60;
const json=(x:any,status=200,headers:any={})=>Response.json(x,{status,headers:{'Cache-Control':'no-store','X-Content-Type-Options':'nosniff','Referrer-Policy':'same-origin',...headers}});
async function handler(req:Request){const env=getRuntimeEnv();const app=new App(env as any);const url=new URL(req.url);const path=url.pathname.replace('/api/','');const post=req.method==='POST';let b:any={};
 try{
 if(path==='webhook/austinpay'&&post){if(!(env as any).AUSTIN_WEBHOOK_SECRET)throw new ServiceError('Webhook belum dikonfigurasi.',503);const raw=await boundedText(req,20000);const supplied=req.headers.get('x-austinpay-signature')||'';const expected=await hmac((env as any).AUSTIN_WEBHOOK_SECRET,raw);if(!/^[a-fA-F0-9]{64}$/.test(supplied)||!constantEqual(supplied.toLowerCase(),expected))throw new ServiceError('Signature webhook tidak valid.',401);const payload=JSON.parse(raw);if(payload.event!==req.headers.get('x-austinpay-event'))throw new ServiceError('Event webhook tidak sesuai.',400);if(payload.event!=='deposit.paid')return json({success:true});if(payload.data?.status!=='paid'||typeof payload.data.transactionId!=='string')throw new ServiceError('Payload webhook tidak valid.',400);const payment=await app.one('SELECT * FROM payments WHERE provider=?',payload.data.transactionId);if(!payment){await app.audit('provider','webhook_unmapped',{provider:payload.data.transactionId});return json({success:true,reconciliation:true});}await app.run('UPDATE payments SET checked=0 WHERE id=?',payment.id);await app.run('INSERT INTO settings VALUES(?,?) ON CONFLICT(id) DO UPDATE SET value=excluded.value','webhook:'+payment.id,JSON.stringify({at:now(),event:payload.event}));return json({success:true,queued:true});}
 if(post){if(req.headers.get('origin')!==url.origin&&path!=='worker')throw new ServiceError('Permintaan tidak diizinkan.',403);if(!path.startsWith('upload')&&(Number(req.headers.get('content-length'))>20000))throw new ServiceError('Data terlalu besar.',400);if(path!=='upload')b=JSON.parse(await boundedText(req,20000));}
 const u=await app.auth(req);const admin=u?.role==='web_admin';const need=()=>{if(!u)throw new ServiceError('Masuk dulu untuk melanjutkan.',401);};
 if(path==='public'&&!env.DB)return json({packages:catalog.map(p=>({...p,spec:JSON.parse(p.spec),preview:true})),settings:{...defaults,service:'Database belum dikonfigurasi'},gateway:false,panel:false,email:false,adminSetup:false,announcements:[],user:null});
 if(path==='public'){const packages=await app.all('SELECT * FROM packages ORDER BY price');return json({packages:packages.length?packages.map((p:any)=>({...p,spec:JSON.parse(p.spec)})):catalog.map(p=>({...p,spec:JSON.parse(p.spec),preview:true})),settings:await app.config(),gateway:!!(env as any).AUSTIN_API_KEY,panel:!!(env as any).PTERO_KEY,email:!!(env as any).EMAIL_RELAY_URL,adminSetup:!!(env as any).ADMIN_SETUP_TOKEN&&u?.email===(env as any).ADMIN_EMAIL&&!await app.one("SELECT id FROM users WHERE role='web_admin'"),announcements:await app.all("SELECT data,created FROM audit WHERE action='announcement' AND json_extract(data,'$.target')='all' ORDER BY created DESC LIMIT 10"),user:u?{id:u.id,name:u.name,username:u.username,email:u.email,role:u.role,balance:u.balance,verified:u.verified}:null});}
 if(['register','login'].includes(path)&&post){await app.rate('auth:'+(req.headers.get('x-vercel-forwarded-for')?.split(',')[0]?.trim()||req.headers.get('x-forwarded-for')?.split(',')[0]?.trim()||req.headers.get('cf-connecting-ip')||'local'),8,300);const email=String(b.email||'').trim().toLowerCase();let person;
 if(path==='register'){if(!/^[a-z0-9_]{3,24}$/.test(b.username)||!/^\S+@\S+\.\S+$/.test(email)||String(b.name||'').trim().length<2||String(b.name).length>80||String(b.password||'').length<10||String(b.password).length>128||b.password!==b.confirm)throw new ServiceError('Lengkapi data. Username 3–24 karakter kecil; password minimal 10 karakter dan konfirmasi harus sama.',400);const salt=random(16);const userId=id();await app.run('INSERT INTO users(id,name,username,email,hash,salt,created) VALUES(?,?,?,?,?,?,?)',userId,b.name.trim(),b.username,email,await password(b.password,salt),salt,now());person=await app.one('SELECT * FROM users WHERE id=?',userId);}
 else{person=await app.one('SELECT * FROM users WHERE email=? OR username=?',email,email);if(!person||await password(String(b.password||''),person.salt)!==person.hash)throw new ServiceError('Email/username atau password tidak sesuai.',400);}
 const token=random();await app.run('INSERT INTO sessions VALUES(?,?,?)',await sha(token),person.id,now()+604800000);return json({ok:true},200,{'Set-Cookie':`felix_session=${token}; HttpOnly; Secure; SameSite=Lax; Path=/; Max-Age=604800`});}
 if(path==='logout'&&post){need();const token=req.headers.get('cookie')?.match(/felix_session=([^;]+)/)?.[1];if(token)await app.run('DELETE FROM sessions WHERE id=?',await sha(token));return json({ok:true},200,{'Set-Cookie':'felix_session=; HttpOnly; Secure; SameSite=Lax; Path=/; Max-Age=0'});}
 if(path==='leaderboard'){const days=url.searchParams.get('period')==='week'?7:url.searchParams.get('period')==='month'?30:36500;const metric=url.searchParams.get('metric')==='amount'?'SUM(o.total)':'COUNT(*)';return json(await app.all(`SELECT u.username,COUNT(*) purchases,SUM(o.total) amount FROM orders o JOIN users u ON u.id=o.user_id WHERE o.status='complete' AND o.payment='paid' AND o.key NOT LIKE 'reseller-%' AND o.created>? GROUP BY u.id ORDER BY ${metric} DESC LIMIT 10`,now()-days*86400000));}
 if(path==='forgot'&&post){if(!(env as any).EMAIL_RELAY_URL)throw new ServiceError('Pemulihan password belum tersedia karena email belum dikonfigurasi. Hubungi admin.');await app.rate('forgot:'+(req.headers.get('x-vercel-forwarded-for')?.split(',')[0]?.trim()||req.headers.get('x-forwarded-for')?.split(',')[0]?.trim()||req.headers.get('cf-connecting-ip')||'local'),3,300);const user=await app.one('SELECT * FROM users WHERE email=?',String(b.email||'').toLowerCase());if(user){const token=random();await app.run('INSERT INTO settings VALUES(?,?)','reset:'+await sha(token),JSON.stringify({userId:user.id,expires:now()+1800000}));await sendEmail(env,user.email,'Pemulihan password FELIX PANEL',url.origin+'/?reset='+token);}return json({message:'Jika akun terdaftar, tautan pemulihan dikirim.'});}
 if(path==='reset'&&post){const key='reset:'+await sha(String(b.token));const r=await app.one('SELECT value FROM settings WHERE id=?',key);if(!r||JSON.parse(r.value).expires<now()||String(b.password).length<10)throw new ServiceError('Tautan tidak berlaku atau password terlalu pendek.',400);const t=JSON.parse(r.value);const salt=random(16);await app.db.batch([app.q('UPDATE users SET hash=?,salt=? WHERE id=?',await password(b.password,salt),salt,t.userId),app.q('DELETE FROM settings WHERE id=?',key),app.q('DELETE FROM sessions WHERE user_id=?',t.userId)]);return json({ok:true});}
 if(path==='verify'&&!post){need();const key='verify:'+await sha(url.searchParams.get('token')||'');const r=await app.one('SELECT value FROM settings WHERE id=?',key);if(!r||JSON.parse(r.value).userId!==u.id||JSON.parse(r.value).expires<now())throw new ServiceError('Tautan verifikasi tidak berlaku.',400);await app.db.batch([app.q('UPDATE users SET verified=1 WHERE id=?',u.id),app.q('DELETE FROM settings WHERE id=?',key)]);return Response.redirect(url.origin+'/?verified=1');}
 if(path==='worker'&&post){if(!(env as any).WORKER_TOKEN||req.headers.get('authorization')!==`Bearer ${(env as any).WORKER_TOKEN}`)throw new ServiceError('Tidak diizinkan.',403);await app.run('DELETE FROM rate_limits WHERE expires<?',now());await app.run('DELETE FROM sessions WHERE expires<?',now());for(const p of await app.all("SELECT id FROM payments WHERE status='pending' ORDER BY checked LIMIT 10")){try{await app.check(p.id);}catch{}}const cfg=await app.config();await app.run("UPDATE orders SET status=CASE WHEN kind='ptero_admin' OR ?=1 THEN 'approval' ELSE 'ready' END WHERE status='settled' AND payment='paid'",cfg.approval?1:0);for(const o of await app.all("SELECT id FROM orders WHERE status IN ('ready','failed') OR (status='provisioning' AND updated<?) LIMIT 10",now()-120000))await app.provision(o.id);
 for(const o of await app.all("SELECT * FROM orders WHERE status='complete' AND expires<? AND kind IN ('panel','ptero_admin')",now())){try{if(o.kind==='panel'&&o.server_id)await ptero(env,`/servers/${o.server_id}/suspend`,'POST');if(o.kind==='ptero_admin'&&o.panel_user){const other=await app.one("SELECT id FROM orders WHERE panel_user=? AND kind='ptero_admin' AND status='complete' AND expires>?",o.panel_user,now());if(!other){const pu=(await ptero(env,`/users/${o.panel_user}`)).attributes;await ptero(env,`/users/${o.panel_user}`,'PATCH',{...pu,root_admin:false});}}await app.run("UPDATE orders SET status='expired' WHERE id=?",o.id);await app.notify(o.user_id,'Masa aktif '+o.invoice+' berakhir.');}catch{await app.admins('Gagal menonaktifkan akses kedaluwarsa: '+o.invoice);}}
 for(const o of await app.all("SELECT id,user_id,invoice FROM orders WHERE status='complete' AND expires BETWEEN ? AND ?",now(),now()+3*86400000)){const mark='reminder:'+o.id;if(!await app.one('SELECT id FROM settings WHERE id=?',mark)){await app.run('INSERT OR IGNORE INTO settings VALUES(?,?)',mark,'true');await app.notify(o.user_id,'Masa aktif '+o.invoice+' berakhir dalam 3 hari.');}}return json({ok:true});}
 need();
 if(path==='bootstrap'&&post){if(!(env as any).ADMIN_SETUP_TOKEN||b.token!==(env as any).ADMIN_SETUP_TOKEN||u.email!==(env as any).ADMIN_EMAIL||await app.one("SELECT id FROM users WHERE role='web_admin'"))throw new ServiceError('Kode aktivasi atau akun tidak sesuai.',403);await app.run("UPDATE users SET role='web_admin' WHERE id=?",u.id);await app.audit(u.id,'bootstrap',{});return json({ok:true});}
 if(path.startsWith('invoice/')){const oid=path.slice(8);const o=await app.one('SELECT * FROM orders WHERE id=? AND (user_id=? OR id IN (SELECT order_id FROM panel_links WHERE user_id=?))',oid,u.id,u.id);if(!o)throw new ServiceError('Invoice tidak ditemukan.',404);return new Response(invoicePdf(o,u),{headers:{'Content-Type':'application/pdf','Content-Disposition':`attachment; filename=${o.invoice}.pdf`,'Cache-Control':'private, no-store'}});}
 if(path==='me'){return json({user:{id:u.id,name:u.name,username:u.username,email:u.email,role:u.role,balance:u.balance,verified:u.verified},reseller:await app.has(u,'reseller'),orders:await Promise.all((await app.all('SELECT * FROM orders WHERE user_id=? OR id IN (SELECT order_id FROM panel_links WHERE user_id=?) ORDER BY created DESC',u.id,u.id)).map((o:any)=>app.safeOrder(o,u))),payments:(await app.all('SELECT * FROM payments WHERE user_id=? AND order_id IS NULL ORDER BY created DESC',u.id)).map((p:any)=>({...p,details:p.details?JSON.parse(p.details):null})),ledger:await app.all('SELECT * FROM ledger WHERE user_id=? ORDER BY created DESC',u.id),notifications:await app.all('SELECT * FROM notifications WHERE user_id=? ORDER BY created DESC LIMIT 100',u.id),requests:await app.all('SELECT * FROM requests WHERE user_id=? ORDER BY created DESC',u.id)});}
 if(path==='profile'&&post){if(b.action==='email'){if(!(env as any).EMAIL_RELAY_URL)throw new ServiceError('Layanan email belum dikonfigurasi.');await app.rate('verify:'+u.id,3,300);const token=random();await app.run('INSERT INTO settings VALUES(?,?)','verify:'+await sha(token),JSON.stringify({userId:u.id,expires:now()+86400000}));await sendEmail(env,u.email,'Verifikasi email FELIX PANEL',url.origin+'/api/verify?token='+token);return json({ok:true});}if(b.password){if(await password(String(b.current||''),u.salt)!==u.hash||String(b.password).length<10)throw new ServiceError('Password lama salah atau password baru kurang dari 10 karakter.',400);const salt=random(16);await app.db.batch([app.q('UPDATE users SET hash=?,salt=? WHERE id=?',await password(b.password,salt),salt,u.id),app.q('DELETE FROM sessions WHERE user_id=?',u.id)]);return json({logout:true});}if(String(b.name||'').length<2||String(b.name).length>80)throw new ServiceError('Nama tidak valid.',400);await app.run('UPDATE users SET name=? WHERE id=?',b.name,u.id);return json({ok:true});}
 if(path==='checkout'&&post)return json(await app.safeOrder(await app.checkout(u,b),u));
 if(path==='quote'&&post){const p=await app.one('SELECT * FROM packages WHERE id=?',b.packageId);if(!p)throw new ServiceError('Paket tidak ditemukan.',404);const discount=await app.discount(u,p,String(b.voucher||''));return json({subtotal:p.price,discount,total:p.price-discount});}
 if(path==='deposit'&&post){const c=await app.config();const a=Number(b.amount);if(!Number.isSafeInteger(a)||a<c.depositMin||a>c.depositMax)throw new ServiceError(`Deposit harus Rp ${c.depositMin} sampai Rp ${c.depositMax}.`,400);const p=await app.createPayment(u,a);return json({...p,details:JSON.parse(p.details)});}
 if(path==='check'&&post){const p=await app.one('SELECT * FROM payments WHERE id=? AND user_id=?',b.id,u.id);if(!p)throw new ServiceError('Pembayaran tidak ditemukan.',404);const r=await app.check(p.id);return json({...r,details:r.details?JSON.parse(r.details):null});}
 if(path==='notifications'&&post){await app.run('UPDATE notifications SET read=1 WHERE user_id=?',u.id);return json({ok:true});}
 if(path==='upload'&&post){if(Number(req.headers.get('content-length'))>3200000)throw new ServiceError('Bukti terlalu besar.',413);const rawUpload=await boundedTextBinary(req,3200000);const f=(await new Request(req.url,{method:'POST',headers:{'Content-Type':req.headers.get('content-type')||''},body:rawUpload}).formData()).get('file') as File;if(!f||f.size>3*1024*1024)throw new ServiceError('Unggah PNG/JPG maksimal 3 MB.',400);const bytes=new Uint8Array(await f.arrayBuffer());const type=bytes[0]===137&&bytes[1]===80&&bytes[2]===78&&bytes[3]===71?'image/png':bytes[0]===255&&bytes[1]===216&&bytes[2]===255?'image/jpeg':null;if(!type)throw new ServiceError('Format bukti harus PNG atau JPG.',400);if(!(env as any).BUCKET)throw new ServiceError('Penyimpanan bukti belum tersedia.');const fileId=id();await (env as any).BUCKET.put(fileId,bytes,{httpMetadata:{contentType:type}});await app.run('INSERT INTO uploads VALUES(?,?,?,?)',fileId,u.id,type,now());return json({id:fileId});}
 if(path.startsWith('file/')){const f=await app.one('SELECT * FROM uploads WHERE id=?',path.slice(5));if(!f||(!admin&&f.user_id!==u.id))throw new ServiceError('Bukti tidak dapat diakses.',403);const obj=await (env as any).BUCKET.get(f.id);if(!obj)throw new ServiceError('Bukti tidak ditemukan.',404);return new Response(obj.body,{headers:{'Content-Type':f.type,'X-Content-Type-Options':'nosniff','Cache-Control':'private, no-store'}});}
 if(path==='accept-customer'&&post){const invite=await app.one("SELECT * FROM requests WHERE id=? AND user_id=? AND kind='customer_link' AND status='pending'",b.id,u.id);if(!invite||!u.verified)throw new ServiceError('Verifikasi email sebelum menerima panel pelanggan.',400);const sourceId=JSON.parse(invite.data).sourceId;const source=await app.one("SELECT * FROM requests WHERE id=? AND status='pending'",sourceId);if(!source)throw new ServiceError('Permintaan tidak tersedia.',400);const d=JSON.parse(source.data);d.customerUserId=u.id;d.customerConsent=true;await app.db.batch([app.q("UPDATE requests SET status='approved' WHERE id=?",invite.id),app.q('UPDATE requests SET data=? WHERE id=?',JSON.stringify(d),source.id)]);await app.notify(source.user_id,'Pelanggan menerima keterkaitan panel. Permintaan siap disetujui admin.');return json({ok:true});}
 if(path==='request'&&post){if(!['warranty','ticket','reseller'].includes(b.kind)||String(b.message||'').length<10||String(b.message).length>4000)throw new ServiceError('Jelaskan permintaan minimal 10 karakter.',400);if(b.evidence&&!await app.one('SELECT id FROM uploads WHERE id=? AND user_id=?',b.evidence,u.id))throw new ServiceError('Bukti tidak valid.',400);
 if(b.kind==='warranty'){const o=await app.one("SELECT * FROM orders WHERE id=? AND user_id=? AND status='complete'",b.orderId,u.id);if(!o||now()>o.created+JSON.parse(o.snapshot).spec.warranty*86400000)throw new ServiceError('Pesanan tidak termasuk periode garansi.',400);}
 if(b.kind==='reseller'){if(!await app.has(u,'reseller')||!b.evidence)throw new ServiceError('Akses reseller aktif dan bukti buyer diperlukan.',403);if(!/^\S+@\S+\.\S+$/.test(String(b.customerEmail||'')))throw new ServiceError('Isi email pelanggan yang benar.',400);b.customerEmail=String(b.customerEmail).toLowerCase();if(!/^[a-zA-Z0-9_-]{3,24}$/.test(b.username)||String(b.server||'').length<3||!['node','python'].includes(b.egg))throw new ServiceError('Data panel pelanggan tidak valid.',400);}
 const rid=id();await app.run('INSERT INTO requests(id,user_id,kind,order_id,data,created) VALUES(?,?,?,?,?,?)',rid,u.id,b.kind,b.orderId||null,JSON.stringify(b),now());await app.admins('Permintaan baru: '+b.kind+' dari '+u.username);if(b.kind==='reseller'){const customer=await app.one('SELECT id,verified FROM users WHERE email=?',b.customerEmail);if(customer){await app.run('INSERT INTO requests(id,user_id,kind,data,created) VALUES(?,?,?,?,?)',id(),customer.id,'customer_link',JSON.stringify({sourceId:rid,message:'Reseller '+u.username+' ingin menautkan panel '+b.server+' ke akun Anda.'}),now());await app.notify(customer.id,'Ada permintaan keterkaitan panel pelanggan. Tinjau di Akun Saya.');}else if((await app.config()).resellerAuto)await approveReseller(app,rid,u);}return json({ok:true});}
 if(path.startsWith('admin')){if(!admin)throw new ServiceError('Akses khusus admin website.',403);
 if(path==='admin'){return json({users:await app.all('SELECT id,name,username,email,role,balance FROM users'),orders:await app.all('SELECT id,invoice,user_id,kind,payment,status,total,reason FROM orders ORDER BY created DESC'),payments:await app.all('SELECT id,user_id,provider,status,amount FROM payments ORDER BY created DESC'),requests:await app.all('SELECT * FROM requests ORDER BY created DESC'),packages:(await app.all('SELECT * FROM packages')).map((p:any)=>({...p,spec:JSON.parse(p.spec)})),vouchers:await app.all('SELECT * FROM vouchers'),audit:await app.all('SELECT * FROM audit ORDER BY created DESC LIMIT 100'),settings:await app.config(),pteroConfig:(await app.one('SELECT value FROM settings WHERE id=?','ptero'))?.value||JSON.stringify({location:Number((env as any).PTERO_LOCATION)||1,eggs:JSON.parse((env as any).PTERO_EGGS||'{}')},null,2)});}
 if(post){await app.audit(u.id,path,{id:b.id||b.code||null,reason:b.reason||null,amount:b.amount??null,price:b.price??null,role:b.role??null,status:b.status??null,action:b.action??null});
 if(path==='admin/init'){for(const p of catalog)await app.run('INSERT OR IGNORE INTO packages VALUES(?,?,?,?,?,?)',p.id,p.kind,p.name,p.price,0,p.spec);return json({ok:true});}
 if(path==='admin/ptero'){const pc=JSON.parse(b.config);if(!Number.isInteger(pc.location)||pc.location<1||!pc.eggs?.node||!pc.eggs?.python)throw new ServiceError('Isi location dan kedua egg.',400);for(const k of ['node','python'])if(!pc.eggs[k].id||!pc.eggs[k].startup||!pc.eggs[k].docker_image)throw new ServiceError('ID, startup, dan docker_image egg wajib.',400);await app.run('INSERT INTO settings VALUES(?,?) ON CONFLICT(id) DO UPDATE SET value=excluded.value','ptero',JSON.stringify(pc));return json({ok:true});}
 if(path==='admin/settings'){const c={...defaults,approval:!!b.approval,resellerAuto:!!b.resellerAuto,depositMin:Number(b.depositMin),depositMax:Number(b.depositMax),service:String(b.service||'').slice(0,200),renewal:!!b.renewal};if(c.depositMin<1000||c.depositMax<c.depositMin)throw new ServiceError('Batas deposit tidak valid.',400);await app.run('INSERT INTO settings VALUES(?,?) ON CONFLICT(id) DO UPDATE SET value=excluded.value','general',JSON.stringify(c));return json({ok:true});}
 if(path==='admin/package'){if(!Number.isSafeInteger(b.price)||b.price<1||!['panel','reseller','ptero_admin'].includes(b.kind)||!b.spec||Number(b.spec.days)<1||Number(b.spec.warranty)<0||String(b.name).length>80)throw new ServiceError('Data paket tidak valid.',400);for(const k of ['ram','cpu','disk','quota'])if(b.spec[k]!==undefined&&(!Number.isSafeInteger(b.spec[k])||b.spec[k]<0))throw new ServiceError('Spesifikasi tidak valid.',400);await app.run('INSERT INTO packages VALUES(?,?,?,?,?,?) ON CONFLICT(id) DO UPDATE SET name=excluded.name,price=excluded.price,active=excluded.active,spec=excluded.spec',String(b.id),b.kind,b.name,b.price,b.active?1:0,JSON.stringify(b.spec));return json({ok:true});}
 if(path==='admin/voucher'){if(!['value','max','min','expires','quota','per_user'].every(k=>Number.isSafeInteger(b[k]))||!['all','panel','reseller','ptero_admin'].includes(b.kind)||!/^[A-Z0-9_-]{3,30}$/.test(b.code)||!['percent','fixed'].includes(b.type)||b.value<1||(b.type==='percent'&&b.value>100)||b.quota<1||b.per_user<1||b.max<1||b.expires<now())throw new ServiceError('Voucher tidak valid.',400);await app.run('INSERT INTO vouchers VALUES(?,?,?,?,?,?,?,?,?)',b.code,b.type,b.value,b.max,b.min,b.kind,b.expires,b.quota,b.per_user);return json({ok:true});}
 if(path==='admin/balance'){if(!Number.isSafeInteger(b.amount)||!b.reason||!await app.one('SELECT id FROM users WHERE id=?',b.id))throw new ServiceError('Isi pengguna, nominal, dan alasan.',400);await app.run('INSERT INTO ledger VALUES(?,?,?,?,?,?)',id(),b.id,b.amount,'adjust:'+id(),b.reason,now());return json({ok:true});}
 if(path==='admin/role'){if(!['buyer','web_admin'].includes(b.role)||b.id===u.id)throw new ServiceError('Role tidak valid atau akun sendiri tidak boleh diubah.',400);await app.run('UPDATE users SET role=? WHERE id=?',b.role,b.id);return json({ok:true});}
 if(path==='admin/order'){const o=await app.one('SELECT * FROM orders WHERE id=?',b.id);if(!o||o.payment!=='paid')throw new ServiceError('Pesanan belum dibayar.',400);if(b.action==='approve'){await app.run("UPDATE orders SET status='ready' WHERE id=? AND status='approval'",o.id);await app.provision(o.id);}else if(b.action==='retry'){await app.provision(o.id);}else if(b.action==='refund'){if(!['failed','approval','ready'].includes(o.status)||o.server_id||!b.reason)throw new ServiceError('Refund hanya untuk pesanan yang belum memiliki server; isi alasan.',400);if(o.kind==='ptero_admin'&&o.status!=='approval')throw new ServiceError('Akses admin yang pernah diaktivasi perlu direkonsiliasi sebelum refund.',400);if(o.kind==='panel'){try{const remote=await ptero(env,'/servers/external/felix-'+o.id);if(remote.attributes)throw new ServiceError('Server ditemukan pada panel. Jalankan retry untuk rekonsiliasi sebelum penanganan refund.',400);}catch(e:any){if(!e.message.includes('(404)'))throw e;}}await app.db.batch([app.q('INSERT INTO ledger VALUES(?,?,?,?,?,?)',id(),o.user_id,o.total,'refund:'+o.id,b.reason,now()),app.q("UPDATE orders SET status='refunded',payment='refunded',reason=? WHERE id=?",b.reason,o.id)]);await app.notify(o.user_id,'Refund '+o.invoice+' masuk ke saldo: '+b.reason);}return json({ok:true});}
 if(path==='admin/request'){const r=await app.one('SELECT * FROM requests WHERE id=?',b.id);if(!r)throw new ServiceError('Permintaan tidak ditemukan.',404);if(r.kind==='reseller'&&b.status==='approved')await approveReseller(app,r.id,u);else{if(!['approved','rejected','processing','complete'].includes(b.status)||!b.reason)throw new ServiceError('Isi status dan alasan.',400);await app.run('UPDATE requests SET status=?,reason=? WHERE id=?',b.status,b.reason,r.id);await app.notify(r.user_id,'Permintaan '+r.kind+': '+b.reason);}return json({ok:true});}
 if(path==='admin/announcement'){if(String(b.message||'').length<3)throw new ServiceError('Isi pengumuman.',400);await app.audit(u.id,'announcement',{message:b.message,target:b.target||'all'});for(const person of await app.all('SELECT id,role FROM users'))if(!b.target||b.target==='all'||person.role===b.target)await app.notify(person.id,b.message);return json({ok:true});}
 if(path==='admin/payment'){const local=await app.one("SELECT * FROM payments WHERE id=? AND status='unknown'",b.id);if(!local||!/^APG-[A-Za-z0-9-]+$/.test(b.transactionId)||!b.reason)throw new ServiceError('Isi transaksi provider dan alasan rekonsiliasi.',400);const hist=await austin(env,'/deposit/history?search='+encodeURIComponent(b.transactionId));const remote=hist.data?.find((x:any)=>x.transaction_id===b.transactionId);if(!remote||remote.amount<local.amount)throw new ServiceError('Transaksi provider belum cocok. Periksa catatan merchant.',400);await app.run("UPDATE payments SET provider=?,details=?,status='pending',checked=0 WHERE id=? AND status='unknown'",b.transactionId,JSON.stringify(remote),local.id);await app.check(local.id);return json({ok:true});}
 if(path==='admin/connections'){const results:any={};try{await austin(env,'/account');results.austin='Terhubung';}catch(e:any){results.austin=e.message;}try{await ptero(env,'/nodes');results.ptero='Terhubung';}catch(e:any){results.ptero=e.message;}return json(results);}
 }}
 throw new ServiceError('Halaman tidak ditemukan.',404);
 }catch(e:any){const msg=e instanceof ServiceError?e.message:String(e?.message).includes('UNIQUE')?'Data sudah digunakan atau transaksi sudah diproses.':String(e?.message).includes('saldo')?'Saldo tidak cukup.':String(e?.message).includes('voucher')?'Kuota voucher tidak tersedia.':'Permintaan belum berhasil. Silakan coba lagi atau hubungi admin.';return json({error:msg},e instanceof ServiceError?e.status:400);}
}
function constantEqual(a:string,b:string){let n=a.length^b.length;for(let i=0;i<b.length;i++)n|=(a.charCodeAt(i)||0)^b.charCodeAt(i);return n===0;}
async function boundedTextBinary(req:Request,max:number){const reader=req.body?.getReader();if(!reader)return new Uint8Array();const chunks=[];let total=0;while(true){const r=await reader.read();if(r.done)break;total+=r.value.length;if(total>max){await reader.cancel();throw new ServiceError('Bukti terlalu besar.',413);}chunks.push(r.value);}const all=new Uint8Array(total);let i=0;for(const c of chunks){all.set(c,i);i+=c.length;}return all;}
async function boundedText(req:Request,max:number){const reader=req.body?.getReader();if(!reader)return '';const parts:Uint8Array[]=[];let size=0;while(true){const r=await reader.read();if(r.done)break;size+=r.value.length;if(size>max){await reader.cancel();throw new ServiceError('Data terlalu besar.',413);}parts.push(r.value);}const bytes=new Uint8Array(size);let off=0;for(const p of parts){bytes.set(p,off);off+=p.length;}return new TextDecoder().decode(bytes);}
async function sendEmail(env:any,to:string,subject:string,link:string){const r=await fetch(env.EMAIL_RELAY_URL,{method:'POST',headers:{Authorization:'Bearer '+env.EMAIL_RELAY_TOKEN,'Content-Type':'application/json'},body:JSON.stringify({to,subject,text:link})});if(!r.ok)throw new ServiceError('Email belum terkirim. Silakan coba lagi.');}
async function approveReseller(app:App,rid:string,admin:any){const r=await app.one('SELECT * FROM requests WHERE id=?',rid);if(!r||r.status!=='pending')return;const owner=await app.one('SELECT * FROM users WHERE id=?',r.user_id);const access=await app.one("SELECT * FROM orders WHERE user_id=? AND kind='reseller' AND status='complete' AND expires>? ORDER BY expires DESC LIMIT 1",owner.id,now());if(!access&&owner.role!=='web_admin')throw new ServiceError('Akses reseller sudah berakhir.',400);const d=JSON.parse(r.data);const customer=await app.one('SELECT id FROM users WHERE email=?',d.customerEmail);if(customer&&!d.customerConsent)throw new ServiceError('Menunggu pelanggan terverifikasi menerima keterkaitan akun.',400);const spec=access?JSON.parse(access.snapshot).spec:{ram:4096,cpu:200,disk:8192,days:30,quota:100,warranty:7};const orderId='reseller-'+rid;
 await app.db.batch([app.q("INSERT INTO orders(id,user_id,invoice,key,kind,total,snapshot,data,payment,status,created) VALUES(?,?,?,?,?,?,?,?,?,?,?)",orderId,owner.id,invoice(),orderId,'panel',0,JSON.stringify({name:'Panel pelanggan',price:0,spec,access:access?.id||null}),JSON.stringify(d),'paid','ready',now()),app.q("UPDATE requests SET status='approved',order_id=? WHERE id=? AND status='pending'",orderId,rid)]);if(d.customerUserId)await app.run('INSERT OR IGNORE INTO panel_links VALUES(?,?,?,?)',id(),d.customerUserId,orderId,now());await app.provision(orderId);await app.notify(owner.id,'Permintaan panel pelanggan disetujui.');}
export const GET=handler;export const POST=handler;
