import {registerHooks} from 'node:module';
import {DatabaseSync} from 'node:sqlite';
import {readFileSync} from 'node:fs';
import assert from 'node:assert/strict';
import {pathToFileURL} from 'node:url';
const root=new URL('../',import.meta.url);let failures=0;let successes=0;
const sql=new DatabaseSync(':memory:');for(const f of ['0000_nosy_wolverine.sql','0001_smart_sunspot.sql','0002_third_lily_hollister.sql'])sql.exec(readFileSync(new URL('drizzle/'+f,root),'utf8'));
function stmt(query,values=[]){return {bind(...v){return stmt(query,v);},async first(){return sql.prepare(query).get(...values)||null;},async all(){return {results:sql.prepare(query).all(...values)};},async run(){const r=sql.prepare(query).run(...values);return {meta:{changes:Number(r.changes)}};}};}
const env={DB:{prepare:stmt,async batch(statements){sql.exec('BEGIN');try{const r=[];for(const s of statements)r.push(await s.run());sql.exec('COMMIT');return r;}catch(e){sql.exec('ROLLBACK');throw e;}}},BUCKET:{files:new Map(),async put(k,v){this.files.set(k,v);},async get(k){return {body:this.files.get(k)};}},AUSTIN_API_KEY:'test-only-not-live',PTERO_KEY:'test-only-not-live',PTERO_URL:'https://panel.test',PTERO_LOCATION:'1',PTERO_EGGS:JSON.stringify({node:{id:1,docker_image:'node:22',startup:'node index.js',environment:{}},python:{id:2,docker_image:'python:3',startup:'python main.py',environment:{}}}),DATA_KEY:'local-test-key'};
globalThis.__felixTestEnv=env;
registerHooks({resolve(s,c,next){if(s==='@/lib/runtime')return {url:'data:text/javascript,export function getRuntimeEnv(){return globalThis.__felixTestEnv}',shortCircuit:true};if(s.startsWith('@/'))return next(new URL(s.slice(2)+'.ts',root).href,c);if(s.startsWith('./')&&c.parentURL?.includes('/lib/')&&!s.endsWith('.ts'))return next(s+'.ts',c);return next(s,c);}});
const {GET,POST}=await import('../app/api/[...path]/route.ts');
const {austin}=await import('../lib/adapters.ts');
const {hmac}=await import('../lib/crypto.ts');
const {App}=await import('../lib/backend.ts');const {invoicePdf}=await import('../lib/pdf.ts');
const app=new App(env);let sequence=0;const deposits=new Map();const users=new Map();const servers=new Map();let serverCreates=0;let failAfterCreate=false;let rejectServer=false;let capturedAustin;
globalThis.fetch=async function(url,options={}){url=new URL(url);const body=options.body?JSON.parse(options.body):{};const response=(x,status=200)=>Response.json(x,{status});if(url.hostname==='austinstore.id'){capturedAustin={url,options};if(url.pathname.endsWith('/deposit/create')){const tx='APG-TEST-'+ ++sequence;deposits.set(tx,'pending');return response({success:true,deposit:{transaction_id:tx,amount:body.amount+23,fee:0,unique_code:23,qr_image:'data:image/png;base64,aGVsbG8=',expired_at:new Date(Date.now()+300000).toISOString(),status:'pending'}});}if(url.pathname.includes('/deposit/check/'))return response({success:true,status:deposits.get(url.pathname.split('/').at(-1))});return response({success:true});}
 if(url.hostname==='panel.test'){const path=url.pathname.replace('/api/application','');if(path.startsWith('/users/external/')){const p=users.get(path.slice(16));return p?response({attributes:p}):response({},404);}if(path==='/users'&&options.method==='POST'){const p={...body,id:users.size+1};users.set(body.external_id,p);return response({attributes:p});}if(path==='/users')return response({data:[]});if(path.startsWith('/users/')&&options.method==='PATCH'){return response({attributes:body});}if(path.startsWith('/servers/external/')){const p=servers.get(path.slice(18));return p?response({attributes:p}):response({},404);}if(path==='/servers'&&options.method==='POST'){if(rejectServer)return response({},503);const p={...body,id:servers.size+1};servers.set(body.external_id,p);serverCreates++;if(failAfterCreate){failAfterCreate=false;throw Error('simulated network lost after provider committed');}return response({attributes:p});}return response({data:[]});}
 throw Error('Unexpected network target in test');};
const origin='https://felix.test';let ip=1;
async function call(path,body,cookie){const req=new Request(origin+'/api/'+path,{method:body?'POST':'GET',headers:{Origin:origin,'Content-Type':'application/json','cf-connecting-ip':'127.0.0.'+ip,...(cookie?{Cookie:cookie}:{})},body:body?JSON.stringify(body):undefined});const r=await (body?POST:GET)(req);const data=await r.json();return {status:r.status,data,cookie:r.headers.get('set-cookie')?.split(';')[0]};}
async function test(name,fn){try{await fn();successes++;console.log('PASS '+name);}catch(e){failures++;console.error('FAIL '+name,e);}}
let buyer,owner,buyerId,ownerId;
await test('Registrasi, hash password, login, uniqueness',async()=>{const r=await call('register',{name:'Buyer Test',username:'buyer_test',email:'buyer@test.id',password:'SecureTest123',confirm:'SecureTest123'});assert.equal(r.status,200);buyer=r.cookie;buyerId=(await call('me',null,buyer)).data.user.id;const user=await app.one('SELECT * FROM users WHERE id=?',buyerId);assert.notEqual(user.hash,'SecureTest123');assert.equal((await call('register',{name:'Buyer Test',username:'buyer_test',email:'buyer@test.id',password:'SecureTest123',confirm:'SecureTest123'})).status,400);assert.equal((await call('login',{email:'buyer@test.id',password:'bad'})).status,400);assert.equal((await call('login',{email:'buyer@test.id',password:'SecureTest123'})).status,200);});
ip++;
await test('RBAC dan kepemilikan di backend',async()=>{assert.equal((await call('checkout',{key:'x'})).status,401);assert.equal((await call('admin',null,buyer)).status,403);assert.equal((await call('request',{kind:'reseller',message:'Saya memiliki buyer',customerEmail:'someone@test.id'},buyer)).status,403);const r=await call('register',{name:'Owner Test',username:'owner_test',email:'owner@test.id',password:'SecureTest123',confirm:'SecureTest123'});owner=r.cookie;ownerId=(await call('me',null,owner)).data.user.id;await app.run("UPDATE users SET role='web_admin' WHERE id=?",ownerId);});
await test('Katalog dan snapshot tidak bergantung perubahan harga',async()=>{assert.equal((await call('admin/init',{},owner)).status,200);await app.run('UPDATE packages SET active=1');await app.run('INSERT INTO ledger VALUES(?,?,?,?,?,?)','test-fund',buyerId,500000,'fund:test','Dana tes',Date.now());await call('admin/settings',{approval:false,resellerAuto:false,depositMin:10000,depositMax:1000000,service:'Mode tes',renewal:true},owner);});
await test('Voucher, checkout saldo atomik dan idempotensi',async()=>{const r=await call('admin/voucher',{code:'TEST5000',type:'fixed',value:5000,max:5000,min:10000,kind:'panel',expires:Date.now()+86400000,quota:1,per_user:1},owner);assert.equal(r.status,200);const body={packageId:'ram-2',server:'bot-test',username:'testpanel',egg:'node',method:'balance',key:'checkout-fixed-test',voucher:'TEST5000'};const first=await call('checkout',body,buyer);assert.equal(first.status,200,JSON.stringify(first.data));assert.equal(first.data.status,'complete');assert.equal(first.data.total,13000);assert.equal((await call('checkout',body,buyer)).data.id,first.data.id);assert.equal((await app.one('SELECT COUNT(*) n FROM ledger WHERE ref=?','order:'+first.data.id)).n,1);assert.equal((await call('quote',{packageId:'ram-2',voucher:'TEST5000'},buyer)).status,400);await app.run('UPDATE packages SET price=99999 WHERE id=?','ram-2');assert.equal(JSON.parse((await app.one('SELECT snapshot FROM orders WHERE id=?',first.data.id)).snapshot).price,18000);await app.run('UPDATE packages SET price=18000 WHERE id=?','ram-2');});
await test('Saldo tidak minus; transaksi gagal dirollback',async()=>{const before=(await app.one('SELECT COUNT(*) n FROM orders')).n;await app.run('UPDATE packages SET price=9999999 WHERE id=?','ram-10');const r=await call('checkout',{packageId:'ram-10',server:'big-panel',username:'bigpanel',egg:'node',method:'balance',key:'insufficient-balance'},buyer);assert.equal(r.status,400);assert.equal((await app.one('SELECT COUNT(*) n FROM orders')).n,before);});
await test('Deposit provider pending tidak menaikkan saldo; paid berulang satu kredit',async()=>{const r=await call('deposit',{amount:50000},buyer);assert.equal(r.status,200);const p=r.data;const before=(await app.one('SELECT balance FROM users WHERE id=?',buyerId)).balance;assert.equal((await call('check',{id:p.id},buyer)).data.status,'pending');assert.equal((await app.one('SELECT balance FROM users WHERE id=?',buyerId)).balance,before);deposits.set(p.provider,'paid');await app.run('UPDATE payments SET checked=0 WHERE id=?',p.id);await call('check',{id:p.id},buyer);await call('check',{id:p.id},buyer);assert.equal((await app.one('SELECT balance FROM users WHERE id=?',buyerId)).balance,before+50000);assert.equal((await app.one('SELECT COUNT(*) n FROM ledger WHERE ref=?','deposit:'+p.id)).n,1);assert.equal((await call('check',{id:p.id},owner)).status,404);});
await test('QRIS order terpisah dari deposit dan dibuat satu kali',async()=>{const r=await call('checkout',{packageId:'ram-3',server:'qris-panel',username:'qrispanel',egg:'python',method:'qris',key:'qris-checkout-test'},buyer);assert.equal(r.status,200,JSON.stringify(r.data));const o=r.data;const before=(await app.one('SELECT balance FROM users WHERE id=?',buyerId)).balance;deposits.set(o.pay.provider,'paid');await call('check',{id:o.pay.id},buyer);await call('check',{id:o.pay.id},buyer);assert.equal((await app.one('SELECT status FROM orders WHERE id=?',o.id)).status,'complete');assert.equal((await app.one('SELECT balance FROM users WHERE id=?',buyerId)).balance,before);assert.equal([...servers.values()].filter(x=>x.external_id==='felix-'+o.id).length,1);});
await test('Kegagalan setelah remote create direkonsiliasi tanpa server ganda',async()=>{failAfterCreate=true;const r=await call('checkout',{packageId:'ram-4',server:'recovery-panel',username:'recoverpanel',egg:'node',method:'balance',key:'failed-provider-order'},buyer);assert.equal(r.status,200);assert.equal(r.data.status,'failed');const count=serverCreates;await call('admin/order',{id:r.data.id,action:'retry'},owner);assert.equal((await app.one('SELECT status FROM orders WHERE id=?',r.data.id)).status,'complete');assert.equal(serverCreates,count);});
await test('Persetujuan admin Pterodactyl tidak memberi role admin website',async()=>{const r=await call('checkout',{packageId:'admin',server:'admin-access',username:'accesspanel',egg:'node',method:'balance',key:'ptero-admin-access'},buyer);assert.equal(r.status,200);assert.equal(r.data.status,'approval');await call('admin/order',{id:r.data.id,action:'approve'},owner);assert.equal((await app.one('SELECT status FROM orders WHERE id=?',r.data.id)).status,'complete');assert.equal((await app.one('SELECT role FROM users WHERE id=?',buyerId)).role,'buyer');assert.equal((await call('admin',null,buyer)).status,403);});
await test('Invoice PDF, klaim garansi, proses dan notifikasi',async()=>{const o=await app.one("SELECT * FROM orders WHERE user_id=? AND kind='panel' AND status='complete' LIMIT 1",buyerId);const pdf=invoicePdf(o,{name:'Buyer Test'});assert.equal(new TextDecoder().decode(pdf).slice(0,8),'%PDF-1.4');const r=await call('request',{kind:'warranty',orderId:o.id,message:'Panel gagal diakses setelah dibuat.'},buyer);assert.equal(r.status,200);const req=await app.one("SELECT * FROM requests WHERE kind='warranty'");assert.equal((await call('admin/request',{id:req.id,status:'processing',reason:'Sedang diperiksa'},owner)).status,200);assert.ok((await app.one('SELECT COUNT(*) n FROM notifications WHERE user_id=?',buyerId)).n>0);});
await test('Reseller membutuhkan bukti dan dapat membuat panel pelanggan',async()=>{await app.run('INSERT INTO ledger VALUES(?,?,?,?,?,?)','test-fund2',buyerId,100000,'fund:test2','Dana tes',Date.now());const r=await call('checkout',{packageId:'reseller',server:'reseller-access',username:'sellerpanel',egg:'node',method:'balance',key:'reseller-access-test'},buyer);assert.equal(r.status,200);assert.equal(r.data.status,'complete');await app.run('INSERT INTO uploads VALUES(?,?,?,?)','proof-test',buyerId,'image/png',Date.now());const req=await call('request',{kind:'reseller',server:'customer-panel',username:'customerpanel',egg:'node',message:'Bukti transaksi buyer terlampir.',customerEmail:'customer@test.id',customerName:'Customer Test',evidence:'proof-test'},buyer);assert.equal(req.status,200,JSON.stringify(req.data));const q=await app.one("SELECT * FROM requests WHERE kind='reseller'");assert.equal((await call('admin/request',{id:q.id,status:'approved',reason:'Buyer terverifikasi'},owner)).status,200);const o=await app.one('SELECT * FROM orders WHERE id=?','reseller-'+q.id);assert.equal(o.status,'complete');assert.equal([...users.values()].find(x=>x.email==='customer@test.id').username,'customerpanel');await call('admin/request',{id:q.id,status:'approved',reason:'Ulang'},owner);assert.equal((await app.one('SELECT COUNT(*) n FROM orders WHERE id=?',o.id)).n,1);});
await test('Leaderboard tidak menghitung deposit atau panel pelanggan gratis',async()=>{const r=await call('leaderboard');assert.equal(r.status,200);const expected=await app.one("SELECT COUNT(*) n FROM orders WHERE user_id=? AND status='complete' AND payment='paid' AND key NOT LIKE 'reseller-%'",buyerId);assert.equal(r.data.find(x=>x.username==='buyer_test').purchases,expected.n);});

await test('Webhook signed, fake signature and replay idempotency',async()=>{env.AUSTIN_WEBHOOK_SECRET='test-webhook-secret';env.WORKER_TOKEN='test-worker-token';const p=(await call('deposit',{amount:30000},buyer)).data;deposits.set(p.provider,'paid');const raw=JSON.stringify({event:'deposit.paid',data:{transactionId:p.provider,amount:p.details.amount,status:'paid'},sentAt:new Date().toISOString()});const signature=await hmac(env.AUSTIN_WEBHOOK_SECRET,raw);const cb=async(sig)=>{const r=await POST(new Request(origin+'/api/webhook/austinpay',{method:'POST',headers:{'Content-Type':'application/json','X-AustinPay-Event':'deposit.paid','X-AustinPay-Signature':sig},body:raw}));return r.status;};assert.equal(await cb('0'.repeat(64)),401);assert.equal(await cb(signature),200);assert.equal(await cb(signature),200);const worker=()=>POST(new Request(origin+'/api/worker',{method:'POST',headers:{Authorization:'Bearer test-worker-token','Content-Type':'application/json'},body:'{}'}));assert.equal((await worker()).status,200);assert.equal((await worker()).status,200);assert.equal((await app.one('SELECT COUNT(*) n FROM ledger WHERE ref=?','deposit:'+p.id)).n,1);});
await test('Snapshot quota reseller et lien client verified consent',async()=>{ip++;const c=await call('register',{name:'Customer Link',username:'customer_link',email:'linked@test.id',password:'SecureTest123',confirm:'SecureTest123'});const cookie=c.cookie;const cu=(await call('me',null,cookie)).data.user.id;const b={kind:'reseller',server:'linked-panel',username:'linkedpanel',egg:'node',message:'Pelanggan ini memiliki akun website.',customerEmail:'linked@test.id',customerName:'Customer Link',evidence:'proof-test'};assert.equal((await call('request',b,buyer)).status,200);const source=await app.one("SELECT * FROM requests WHERE kind='reseller' ORDER BY created DESC LIMIT 1");const invite=await app.one("SELECT * FROM requests WHERE kind='customer_link' AND user_id=?",cu);assert.equal((await call('admin/request',{id:source.id,status:'approved',reason:'Test'},owner)).status,400);assert.equal((await call('accept-customer',{id:invite.id},cookie)).status,400);await app.run('UPDATE users SET verified=1 WHERE id=?',cu);assert.equal((await call('accept-customer',{id:invite.id},cookie)).status,200);assert.equal((await call('admin/request',{id:source.id,status:'approved',reason:'Test'},owner)).status,200);const own=(await call('me',null,cookie)).data;assert.ok(own.orders.some(o=>o.id==='reseller-'+source.id));});
await test('Provisioning interrompu reprend apres lease sans double serveur',async()=>{rejectServer=true;const o=(await call('checkout',{packageId:'ram-1',server:'lease-panel',username:'leasepanel',egg:'node',method:'balance',key:'lease-recovery-test'},buyer)).data;assert.equal(o.status,'failed');await app.run("UPDATE orders SET status='provisioning',updated=? WHERE id=?",Date.now()-130000,o.id);rejectServer=false;await app.provision(o.id);assert.equal((await app.one('SELECT status FROM orders WHERE id=?',o.id)).status,'complete');});

await test('HMAC request tanpa query dan raw body konsisten',async()=>{env.AUSTIN_API_SECRET='test-api-secret';await austin(env,'/deposit/history?search=APG-TEST-1');const h=capturedAustin.options.headers;const expected=await hmac(env.AUSTIN_API_SECRET,'GET\n/api/deposit/history\n\n'+h['X-Timestamp']);assert.equal(h['X-Signature'],expected);delete env.AUSTIN_API_SECRET;});
await test('Upload magic bytes, ukuran dan pemilik',async()=>{const form=new FormData();form.set('file',new File([new Uint8Array([137,80,78,71,13,10,26,10])],'proof.png',{type:'image/png'}));const response=await POST(new Request(origin+'/api/upload',{method:'POST',headers:{Origin:origin,Cookie:buyer},body:form}));assert.equal(response.status,200);const file=await response.json();assert.equal((await GET(new Request(origin+'/api/file/'+file.id,{headers:{Cookie:owner}}))).status,200);const bad=new FormData();bad.set('file',new File(['<html>not an image</html>'],'proof.png',{type:'image/png'}));assert.equal((await POST(new Request(origin+'/api/upload',{method:'POST',headers:{Origin:origin,Cookie:buyer},body:bad}))).status,400);});

await test('Perpanjangan panel kedaluwarsa tanpa server baru',async()=>{const base=await app.one("SELECT * FROM orders WHERE kind='panel' AND user_id=? AND status='complete' LIMIT 1",buyerId);await app.run("UPDATE orders SET status='expired',expires=? WHERE id=?",Date.now()-86400000,base.id);const before=serverCreates;const d=JSON.parse(base.data);const snap=JSON.parse(base.snapshot);const r=await call('checkout',{packageId:snap.id,server:d.server,username:d.username,egg:d.egg,method:'balance',renew:base.id,key:'renew-expired-test'},buyer);assert.equal(r.status,200,JSON.stringify(r.data));assert.equal(r.data.status,'complete');assert.equal(serverCreates,before);assert.equal((await app.one('SELECT status FROM orders WHERE id=?',base.id)).status,'complete');});
console.log(`\n${successes} passed / ${failures} failed. Provider simulasi; tidak ada pembayaran atau provisioning live.`);if(failures)process.exit(1);
